services:
  - type: worker
    name: nexadev-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GUILD_ID
        sync: false
      - key: TICKET_CHANNEL_ID
        sync: false
      - key: VERIFY_CHANNEL_ID
        sync: false
      - key: STATUS_CHANNEL_ID
        sync: false
      - key: STAFF_ROLE_ID
        sync: false
